# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: ja-JP
tone_instructions: 丁寧で優しい言葉遣いで、具体的な改善点を指摘してください。また、良い点があればたまには褒めてください。
reviews:
  profile: assertive
  high_level_summary_in_walkthrough: true
  poem: false
  path_filters:
    - "!dist/**"
    - "!**/*.app"
    - "!**/*.bin"
    - "!**/*.bz2"
    - "!**/*.class"
    - "!**/*.db"
    - "!**/*.csv"
    - "!**/*.tsv"
    - "!**/*.dat"
    - "!**/*.dll"
    - "!**/*.dylib"
    - "!**/*.egg"
    - "!**/*.glif"
    - "!**/*.gz"
    - "!**/*.xz"
    - "!**/*.zip"
    - "!**/*.7z"
    - "!**/*.rar"
    - "!**/*.zst"
    - "!**/*.ico"
    - "!**/*.jar"
    - "!**/*.tar"
    - "!**/*.war"
    - "!**/*.lo"
    - "!**/*.log"
    - "!**/*.mp3"
    - "!**/*.wav"
    - "!**/*.wma"
    - "!**/*.mp4"
    - "!**/*.avi"
    - "!**/*.mkv"
    - "!**/*.wmv"
    - "!**/*.m4a"
    - "!**/*.m4v"
    - "!**/*.3gp"
    - "!**/*.3g2"
    - "!**/*.rm"
    - "!**/*.mov"
    - "!**/*.flv"
    - "!**/*.iso"
    - "!**/*.swf"
    - "!**/*.flac"
    - "!**/*.nar"
    - "!**/*.o"
    - "!**/*.ogg"
    - "!**/*.otf"
    - "!**/*.p"
    - "!**/*.pdf"
    - "!**/*.doc"
    - "!**/*.docx"
    - "!**/*.xls"
    - "!**/*.xlsx"
    - "!**/*.map"
    - "!**/*.out"
    - "!**/*.ppt"
    - "!**/*.pptx"
    - "!**/*.pkl"
    - "!**/*.pickle"
    - "!**/*.pyc"
    - "!**/*.pyd"
    - "!**/*.pyo"
    - "!**/*.pub"
    - "!**/*.pem"
    - "!**/*.rkt"
    - "!**/*.so"
    - "!**/*.ss"
    - "!**/*.eot"
    - "!**/*.exe"
    - "!**/*.pb.go"
    - "!**/*.pb.gw.go"
    - "!**/*.lock"
    - "!**/*.ttf"
    - "!**/*.yaml"
    - "!**/*.yml"
    - "!**/*.xml"
    - "!**/*.cfg"
    - "!**/*.toml"
    - "!**/*.ini"
    - "!**/*.mod"
    - "!**/*.sum"
    - "!**/*.work"
    - "!**/*.json"
    - "!**/*.mmd"
    - "!**/*.svg"
    - "!**/*.jpeg"
    - "!**/*.jpg"
    - "!**/*.png"
    - "!**/*.gif"
    - "!**/*.bmp"
    - "!**/*.tiff"
    - "!**/*.webm"
    - "!**/*.woff"
    - "!**/*.woff2"
    - "!**/*.dot"
    - "!**/*.md5sum"
    - "!**/*.wasm"
    - "!**/*.snap"
    - "!**/*.parquet"
    - "!**/gen/**"
    - "!**/_gen/**"
    - "!**/generated/**"
    - "!**/@generated/**"
    - "!**/vendor/**"
    - "!**/*.min.js"
    - "!**/*.min.js.map"
    - "!**/*.min.js.css"
    - "!**/*.tfstate"
    - "!**/*.tfstate.backup"
    - "!.kiro/steering/**"
    - "!.kiro/specs/**"
  auto_review:
    drafts: true
