/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/test/auth': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** @constant */
              message: 'api auth test'
            }
          }
        }
        401: components['responses']['AuthenticationException']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/spa/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['spa.login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/spa/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['spa.logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/spa/user': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['spa.user']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** LoginRequest */
    LoginRequest: {
      /** Format: email */
      email: string
      password: string
      remember?: boolean
    }
    /** MinimumUserResource */
    MinimumUserResource: {
      id: number
      name: string
    }
  }
  responses: {
    /** @description Validation error */
    ValidationException: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description Errors overview. */
          message: string
          /** @description A detailed description of each field that failed validation. */
          errors: {
            [key: string]: string[]
          }
        }
      }
    }
    /** @description Unauthenticated */
    AuthenticationException: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description Error overview. */
          message: string
        }
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  'spa.login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            user: components['schemas']['MinimumUserResource']
          }
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            message: null | unknown[] | string
          }
        }
      }
      422: components['responses']['ValidationException']
    }
  }
  'spa.logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['AuthenticationException']
    }
  }
  'spa.user': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            user: components['schemas']['MinimumUserResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
    }
  }
}
