/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'sanctum.csrf-cookie': []
    'spa.login': []
    'spa.logout': []
    'auth.user': []
    'storage.local': [
      {
        name: 'path'
        required: true
      },
    ]
  }
}
export {}
